name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Install dependencies
        run: pnpm install
      - run: |
          echo DATABASE_URL="${{ secrets.DATABASE_URL }}" >> .env
          echo NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}" >> .env
          echo DISCORD_CLIENT_ID="${{ secrets.DISCORD_CLIENT_ID }}" >> .env
          echo DISCORD_CLIENT_SECRET="${{ secrets.DISCORD_CLIENT_SECRET }}" >> .env
      - name: buid
        run: pnpm build
